public class Operadores {

        public static void main(String[] args) {
    
           int numero = 5;
           //numero = numero + 1; 
           System.out.println( ++ numero);
           // mesma regra para diminuir "--" valores em 1
           
           // pode-se altenar o valor de uma boolean com o sinal "!"
           boolean variavel = true;
           
           variavel = !variavel;
           System.out.println(variavel);
           
        
        }
    // exemplo de usando o if e else com os simbolos "?" e ":"
        public static void man(String[] args) {

            int a, b;
            a = 6;
            b = 5;

            String resultado = a == b ? "verdadeiro" : "falso";

            System.out.println(resultado);
        }
    }

